#!/usr/bin/env bash
# This is a script to check for the sub domains and records.


# Checking the subdomains
get_subdomain_info() {
	query=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr "\t" "\n" | tail -2 | tr "\n" " ")
	echo "$2" "$query" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

# Display info for entire subdomains if only 1 arg (domain) is provided, but
# if 2 args (doamin and subdomain) are provided, display info for the specified subdomain
if [ "$#" == 1 ]; then
	get_subdomain_info "$1" "www"
	get_subdomain_info "$1" "lb-01"
	get_subdomain_info "$1" "web-01"
	get_subdomain_info "$1" "web-02"

	elif [ "$#" == 2 ]; then
		get_subdomain_info "$1" "$2"
	fi